### ISSUE TITLE
enhancement of vis3D?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [DataKnowledge/vis3D#1]
I've seen the great job made by Nicole White with python, the ipython notebook & visjs.org library.

The 3D graph is really impressive.  See here: http://nicolewhite.github.io/neo4j-jupyter/twitter.html

Do you have plan to enhance this library?

It would be a pity to have R lagging behind... :)

**Comment by bthieurmel** [comment]
Hi,
I think the 3D graph you are talking about is not construct with vis.js but other library.
vis.js 3D graph looks like this : http://visjs.org/graph3d_examples.html, and the full API is in the R package.
Actually, there is not 3D possibility with network using vis.js
